name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: cargo build --verbose --release

    - name: Formatting
      run: cargo fmt --check

    - name: Lint
      run: cargo clippy -- --deny warnings

    - name: Test
      run: cargo test --verbose
