name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        rust-channel: [stable, nightly]

    steps:
    - uses: actions/checkout@v2

    - uses: actions-rs/toolchain@v1
      with:
          toolchain: ${{ matrix.rust-channel }}
          override: true
          components: rustfmt, clippy

    - name: Build
      run: cargo build --verbose --release

    - name: Formatting
      run: cargo fmt --check

    - name: Lint
      run: cargo clippy -- --deny warnings

    - name: Test
      run: cargo test --verbose
